### DISCUSSION TITLE
Potential design changes?

### DISCUSSION THREAD

**Discussion by Lakitna** [sxdjt/horizontal-waterfall-history-card#38] [Ideas]
Now that card_mod is working again, I went a little nuts with design options. I like playing around with this kind of stuff, and maybe there are some ideas in here that you'd like to incorporate. If not, no worries.

Please let me know what you think :)

## Baseline

Normal and compact without any card mod changes

![image](https://github.com/user-attachments/assets/ad5618ac-5066-43a5-9cd6-21bd0a4ad153)

As you can see from the stuff below, I prefer the compact one.

Since I prefer the compact version, I pushed to take the concept further. In all designs below:

- I removed the waterfall bar borders. I don't like the separation the borders create. Especially when using the gradient option.
- I extended the waterfall to be 100% width. The padding on the side of the waterfall feels a bit like wasted space. At the same time, the padding on the top and bottom doesn't feel like that. With 100% I may have pushed it a bit too far though 🤷‍♂️

## Text works like wings

By matching the card border radius on the waterfall, you get this neat effect where the header and footer feel like they slide out from behind the waterfall.

In some situations, you may not want a header or footer. If there is no content in there, they should disappear.

![image](https://github.com/user-attachments/assets/cb8aa623-a8ee-4c64-9ca2-a263939f9a6f)

<details>
<summary>Code</summary>

### Card 1

```yaml
type: custom:waterfall-history-card
entity: sensor.dehumidifier_living_room_humidity
title: Indoor humidity
icon: mdi:water-percent
compact: true
default_value: null
digits: 1
gradient: true
height: 60
hours: 24
intervals: 144
max_value: 100
min_value: 0
columns: 24
show_current: true
show_labels: true
show_min_max: true
thresholds:
  - value: 0
    color: "#4FC3F7"
  - value: 45
    color: "#81C784"
  - value: 75
    color: "#FFB74D"
  - value: 100
    color: "#FF8A65"
card_mod:
  style: |-
    .bar-segment {
      border: none;
    }
    .bar-segment:hover {
      transform: none;
    }
    .gradient-overlay {
      display: none;
    }
    :host {
      padding: 8px 0 0 0;
      overflow: clip;
    }
    .waterfall-container {
      border-radius: 12px;
    }
    .card-header {
      margin-top: -4px;
      margin-left: 12px;
      margin-right: 12px;
      padding-bottom: 4px;
    }
    .labels {
      margin-top: 2px;
      margin-left: 12px;
      margin-right: 12px;
    }
    .current-value {
      font-weight: normal;
    }
```

### Card 2

```yaml
type: custom:waterfall-history-card
entity: sensor.dehumidifier_living_room_humidity
title: Indoor humidity
icon: mdi:water-percent
compact: true
default_value: null
digits: 1
gradient: true
height: 60
hours: 24
intervals: 144
max_value: 100
min_value: 0
columns: 24
show_current: true
show_labels: false
show_min_max: false
thresholds:
  - value: 0
    color: "#4FC3F7"
  - value: 45
    color: "#81C784"
  - value: 75
    color: "#FFB74D"
  - value: 100
    color: "#FF8A65"
card_mod:
  style: |-
    .bar-segment {
      border: none;
    }
    .bar-segment:hover {
      transform: none;
    }
    .gradient-overlay {
      display: none;
    }
    :host {
      padding: 8px 0 0 0;
      overflow: clip;
    }
    .waterfall-container {
      border-radius: 12px;
    }
    .card-header {
      margin-top: -4px;
      margin-left: 12px;
      margin-right: 12px;
      padding-bottom: 4px;
    }
    .labels {
      margin-left: 12px;
      margin-right: 12px;
    }
    .current-value {
      font-weight: normal;
    }
```

```yaml
type: custom:waterfall-history-card
entity: sensor.dehumidifier_living_room_humidity
title: Indoor humidity
icon: mdi:water-percent
compact: true
default_value: null
digits: 1
gradient: true
height: 60
hours: 24
intervals: 144
max_value: 100
min_value: 0
columns: 24
show_current: false
show_labels: true
show_min_max: true
thresholds:
  - value: 0
    color: "#4FC3F7"
  - value: 45
    color: "#81C784"
  - value: 75
    color: "#FFB74D"
  - value: 100
    color: "#FF8A65"
card_mod:
  style: |-
    .bar-segment {
      border: none;
    }
    .bar-segment:hover {
      transform: none;
    }
    .gradient-overlay {
      display: none;
    }
    :host {
      padding: 8px 0 0 0;
      overflow: clip;
    }
    .waterfall-container {
      border-radius: 12px;
    }
    .card-header {
      display: none;
    }
    .labels {
      margin-left: 12px;
      margin-right: 12px;
      margin-top: 2px;
    }
```

</details>

## Transparent overlay bars

Instead of having the header and footer be outside of the waterfall, make it part of it. To keep the text readable, they need a semi-transparent background.

![image](https://github.com/user-attachments/assets/36b90481-b064-4230-a529-f922e488a5d7)

<details>
<summary>Code</summary>

### Card 1

```yaml
type: custom:waterfall-history-card
entity: sensor.dehumidifier_living_room_humidity
title: Indoor humidity
icon: mdi:water-percent
compact: true
default_value: null
digits: 1
gradient: true
height: 100
hours: 24
intervals: 144
max_value: 100
min_value: 0
columns: 24
show_current: true
show_labels: true
show_min_max: true
thresholds:
  - value: 0
    color: "#4FC3F7"
  - value: 45
    color: "#81C784"
  - value: 75
    color: "#FFB74D"
  - value: 100
    color: "#FF8A65"
card_mod:
  style: |-
    .bar-segment {
      border: none;
    }
    .bar-segment:hover {
      transform: none;
    }
    .gradient-overlay {
      display: none;
    }
    :host {
      padding: 8px 0 0 0;
      overflow: clip
    }
    .card-header, .labels, .min-max-label {
      position: absolute;
      padding-top: 2px;
      padding-bottom: 2px;
      background-color: rgba(0,0,0,.5);
      width: 100%;
    }
    .card-header {
      z-index: 10;
      top: 0;
    }
    .card-header > * {
      padding: 0 4px;
    }

    .labels, .min-max-label {
      margin-top: -20px;
    }
    .min-max-label {
      background: none;
      color: rgba(255,255,255,.9);
    }
    .labels .time-label {
      margin: 0 8px;
      color: rgba(255,255,255,.9);
    }
```

### Card 2

```yaml
type: custom:waterfall-history-card
entity: sensor.dehumidifier_living_room_humidity
title: Indoor humidity
icon: mdi:water-percent
compact: true
default_value: null
digits: 1
gradient: true
height: 80
hours: 24
intervals: 144
max_value: 100
min_value: 0
columns: 24
show_current: true
show_labels: false
show_min_max: false
thresholds:
  - value: 0
    color: "#4FC3F7"
  - value: 45
    color: "#81C784"
  - value: 75
    color: "#FFB74D"
  - value: 100
    color: "#FF8A65"
card_mod:
  style: |-
    .bar-segment {
      border: none;
    }
    .bar-segment:hover {
      transform: none;
    }
    .gradient-overlay {
      display: none;
    }
    :host {
      padding: 8px 0 0 0;
      overflow: clip
    }
    .card-header, .labels, .min-max-label {
      position: absolute;
      padding-top: 2px;
      padding-bottom: 2px;
      background-color: rgba(0,0,0,.5);
      width: 100%;
    }
    .card-header {
      z-index: 10;
      top: 0;
    }
    .card-header > * {
      padding: 0 4px;
    }

    .labels, .min-max-label {
      margin-top: -20px;
    }
    .min-max-label {
      background: none;
      color: rgba(255,255,255,.9);
    }
    .labels .time-label {
      margin: 0 8px;
      color: rgba(255,255,255,.9);
    }
```

### Card 3

```yaml
type: custom:waterfall-history-card
entity: sensor.dehumidifier_living_room_humidity
title: Indoor humidity
icon: mdi:water-percent
compact: true
default_value: null
digits: 1
gradient: true
height: 80
hours: 24
intervals: 144
max_value: 100
min_value: 0
columns: 24
show_current: false
show_labels: true
show_min_max: true
thresholds:
  - value: 0
    color: "#4FC3F7"
  - value: 45
    color: "#81C784"
  - value: 75
    color: "#FFB74D"
  - value: 100
    color: "#FF8A65"
card_mod:
  style: |-
    .bar-segment {
      border: none;
    }
    .bar-segment:hover {
      transform: none;
    }
    .gradient-overlay {
      display: none;
    }
    :host {
      padding: 8px 0 0 0;
      overflow: clip
    }
    .card-header {
      display: none;
    }
    .labels, .min-max-label {
      margin-top: -20px;
      padding-top: 2px;
      padding-bottom: 2px;
      position: absolute;
      background-color: rgba(0,0,0,.5);
      width: 100%;
    }
    .min-max-label {
      background: none;
      color: rgba(255,255,255,.9);
    }
    .labels .time-label {
      margin: 0 8px;
      color: rgba(255,255,255,.9);
    }
```

</details>

## Transparent overlay sections

The previous design uses a lot of semi-transparent things with no text on them. Remove those so you can see more of the pretty waterfall.

Note: The width of the min-max-label should be matched to the text (so narrower than the screenshot), but that would require HTML changes, so I couldn't do it with card_mod, so 🤷‍♂️🤷‍♂️. Consider this part to be a sketch instead of a polished product.

![image](https://github.com/user-attachments/assets/86e61400-f734-4f19-9114-0166f5bdea3f)

There is also this version that radically simplifies the data

![image](https://github.com/user-attachments/assets/5ee48c68-d232-44a3-b8d5-7579bc4ea4b2)

<details>
<summary>Code</summary>

### Card 1

```yaml
type: custom:waterfall-history-card
entity: sensor.dehumidifier_living_room_humidity
title: Indoor humidity
icon: mdi:water-percent
compact: true
default_value: null
digits: 1
gradient: true
height: 80
hours: 24
intervals: 144
max_value: 100
min_value: 0
columns: 24
show_current: true
show_labels: true
show_min_max: true
thresholds:
  - value: 0
    color: "#4FC3F7"
  - value: 45
    color: "#81C784"
  - value: 75
    color: "#FFB74D"
  - value: 100
    color: "#FF8A65"
card_mod:
  style: |-
    .bar-segment {
      border: none;
    }
    .bar-segment:hover {
      transform: none;
    }
    .gradient-overlay {
      display: none;
    }
    :host {
      padding: 8px 0 0 0;
      overflow: clip;
    }

    .card-header, .labels, .min-max-label {
      position: absolute;
      width: 100%;
    }
    .card-header {
      z-index: 10;
      top: 0;
    }
    .labels, .min-max-label {
      margin-top: -20px;
    }
    .labels .time-label, .min-max-label, .card-header > * {
      padding: 2px 8px;
      background-color: rgba(0,0,0,.5);
      color: rgba(255,255,255,.9);
      border-radius: 2px;
    }
    .min-max-label {
      width: 20%;
      margin-left: auto;
      margin-right: auto;
      left: 40%;
    }
```

### Card 2

```yaml
type: custom:waterfall-history-card
entity: sensor.dehumidifier_living_room_humidity
title: Indoor humidity
icon: mdi:water-percent
compact: true
default_value: null
digits: 1
gradient: true
height: 80
hours: 24
intervals: 144
max_value: 100
min_value: 0
columns: 24
show_current: true
show_labels: false
show_min_max: false
thresholds:
  - value: 0
    color: "#4FC3F7"
  - value: 45
    color: "#81C784"
  - value: 75
    color: "#FFB74D"
  - value: 100
    color: "#FF8A65"
card_mod:
  style: |-
    .bar-segment {
      border: none;
    }
    .bar-segment:hover {
      transform: none;
    }
    .gradient-overlay {
      display: none;
    }
    :host {
      padding: 8px 0 0 0;
      overflow: clip;
    }

    .card-header, .labels, .min-max-label {
      position: absolute;
      width: 100%;
    }
    .card-header {
      z-index: 10;
      top: 0;
    }
    .labels, .min-max-label {
      margin-top: -20px;
    }
    .labels .time-label, .min-max-label, .card-header > * {
      padding: 2px 8px;
      background-color: rgba(0,0,0,.5);
      color: rgba(255,255,255,.9);
      border-radius: 2px;
    }
    .min-max-label {
      width: 20%;
      margin-left: auto;
      margin-right: auto;
      left: 40%;
    }
```

### Card 3

```yaml
type: custom:waterfall-history-card
entity: sensor.dehumidifier_living_room_humidity
title: Indoor humidity
icon: mdi:water-percent
compact: true
default_value: null
digits: 1
gradient: true
height: 80
hours: 24
intervals: 144
max_value: 100
min_value: 0
columns: 24
show_current: false
show_labels: true
show_min_max: true
thresholds:
  - value: 0
    color: "#4FC3F7"
  - value: 45
    color: "#81C784"
  - value: 75
    color: "#FFB74D"
  - value: 100
    color: "#FF8A65"
card_mod:
  style: |-
    .bar-segment {
      border: none;
    }
    .bar-segment:hover {
      transform: none;
    }
    .gradient-overlay {
      display: none;
    }
    :host {
      padding: 8px 0 0 0;
      overflow: clip;
    }
    .card-header {
      display: none;
    }
    .labels, .min-max-label {
      margin-top: -20px;
      position: absolute;
      width: 100%;
    }
    .labels .time-label, .min-max-label {
      padding: 2px 8px;
      background-color: rgba(0,0,0,.5);
      color: rgba(255,255,255,.9);
      border-radius: 2px;
    }
    .min-max-label {
      width: 20%;
      margin-left: auto;
      margin-right: auto;
      left: 40%;
    }
```

### Card 4

```yaml
type: custom:waterfall-history-card
entity: sensor.dehumidifier_living_room_humidity
title: Indoor humidity
icon: mdi:water-percent
compact: true
default_value: null
digits: 1
gradient: true
height: 80
hours: 24
intervals: 144
max_value: 100
min_value: 0
columns: 24
show_current: true
show_labels: false
show_min_max: false
thresholds:
  - value: 0
    color: "#4FC3F7"
  - value: 45
    color: "#81C784"
  - value: 75
    color: "#FFB74D"
  - value: 100
    color: "#FF8A65"
card_mod:
  style: |-
    .bar-segment {
      border: none;
    }
    .bar-segment:hover {
      transform: none;
    }
    .gradient-overlay {
      display: none;
    }
    :host {
      padding: 8px 0 0 0;
      overflow: clip;
    }

    .card-header, .labels, .min-max-label {
      position: absolute;
      width: 100%;
    }
    .card-header {
      z-index: 10;
      top: 0;
      justify-content: left;
    }
    .labels, .min-max-label {
      margin-top: -20px;
    }
    .labels .time-label, .min-max-label, .card-header > * {
      padding: 2px 6px 2px 6px;
      background-color: rgba(0,0,0,.5);
      color: rgba(255,255,255,.9);
      border-radius: 0;
    }
    .min-max-label {
      width: 20%;
      margin-left: auto;
      margin-right: auto;
      left: 40%;
    }
```

</details>

## Just overlay it

Instead of trying to create nice carveouts for the data, why not slap it on top? To make this readable, the text still needs contrast, though. The dark gradient/background combined with the dark text shadow makes the light text reasonably readable.

The icons are pretty. Let's use them for visual interest.

![image](https://github.com/user-attachments/assets/77ae5bb1-dfe4-4ac1-b1d3-36123d0de26b)

<details>
<summary>Code</summary>

### Card 1

```yaml
type: custom:waterfall-history-card
entity: sensor.dehumidifier_living_room_humidity
title: Indoor humidity
icon: mdi:water-percent
compact: true
default_value: null
digits: 1
gradient: true
height: 80
hours: 24
intervals: 144
max_value: 100
min_value: 0
columns: 24
show_current: true
show_labels: false
show_min_max: false
thresholds:
  - value: 0
    color: "#4FC3F7"
  - value: 45
    color: "#81C784"
  - value: 75
    color: "#FFB74D"
  - value: 100
    color: "#FF8A65"
card_mod:
  style: |-
    .bar-segment {
      border: none;
    }
    .bar-segment:hover {
      transform: none;
    }
    .gradient-overlay {
      left: 0;
      width: 50%;
      background: linear-gradient(to left, transparent, rgba(0, 0, 0, 0.4));
    }
    :host {
      padding: 8px 0 0 0;
      overflow: clip;
    }

    .card-header, .labels, .min-max-label {
      position: absolute;
      width: 100%;
      height: 100%;
    }
    .card-header {
      z-index: 10;
      top: 0;
      justify-content: left;
      pointer-events: none;
    }
    .labels, .min-max-label {
      margin-top: -20px;
    }
    .labels .time-label, .min-max-label, .card-header > * {
      padding: 2px 6px 2px 6px;
      color: rgba(255,255,255,.9);
      border-radius: 0;
      text-shadow: 0 0 15px rgba(0,0,0,.8);
    }
    .card-header ha-icon {
      --mdc-icon-size: 5em;
    }
```

### Card 2

```yaml
type: custom:waterfall-history-card
entity: sensor.dehumidifier_living_room_humidity
title: Indoor humidity
icon: mdi:water-percent
compact: true
default_value: null
digits: 1
gradient: true
height: 80
hours: 24
intervals: 144
max_value: 100
min_value: 0
columns: 24
show_current: true
show_labels: false
show_min_max: false
thresholds:
  - value: 0
    color: "#4FC3F7"
  - value: 45
    color: "#81C784"
  - value: 75
    color: "#FFB74D"
  - value: 100
    color: "#FF8A65"
card_mod:
  style: |-
    .bar-segment {
      border: none;
    }
    .bar-segment:hover {
      transform: none;
    }
    .gradient-overlay {
      display: none;
    }
    :host {
      padding: 8px 0 0 0;
      overflow: clip;
    }

    .card-header, .labels, .min-max-label {
      position: absolute;
      width: 100%;
      height: 100%;
    }
    .card-header {
      z-index: 10;
      top: 0;
      justify-content: left;
      background: rgba(0,0,0,.2);
      width: auto;
      padding-right: .5em;
      pointer-events: none;
    }
    .labels, .min-max-label {
      margin-top: -20px;
    }
    .labels .time-label, .min-max-label, .card-header > * {
      padding: 2px 6px 2px 6px;
      color: rgba(255,255,255,.9);
      border-radius: 0;
      text-shadow: 0 0 15px rgba(0,0,0,.8);
    }
    .card-header ha-icon {
      --mdc-icon-size: 5em;
    }
```

</details>
