### ISSUE TITLE
Card mod styling does not apply

### ISSUE THREAD

**Issue by Lakitna** [sxdjt/horizontal-waterfall-history-card#35]
I've been playing around with this great-looking card, and it seems like the card-mod support does not work.

I added the following custom styling. I was just playing around to see what's possible and stuff :)

```yaml
card_mod:
  style: |-
    :host {
      --card-background-color: #ff0000;
      border-width: 0 !important;
      padding: 0 !important;
    }
    .current-value {
      display: none !important;
    }
```

However, none of this styling seems to apply:

![Image](https://github.com/user-attachments/assets/27feb798-db06-40cc-8a34-9cf4fda8f158)
